"""changed item ingredients to item description

Revision ID: c140c31ef767
Revises: 548cfa5daa01
Create Date: 2023-08-25 21:09:20.613686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c140c31ef767'
down_revision: Union[str, None] = '548cfa5daa01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('items', 'ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('ingredients', sa.VARCHAR(), nullable=True))
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
